name: backend-ci

on:
  push:
    branches:
      - main
      - 'feat/**'
      - 'fix/**'
      - 'chore/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # ⬅️ 모든 run 스텝이 레포 루트에서 실행되도록 고정
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 디버그: 현재 위치/파일 확인 (첫 실행에서만 보고 이후 삭제해도 됨)
      - name: Where am I?
        run: pwd && ls -la

      - name: Set up JDK 17 (with Gradle cache)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build (tests skipped for now)
        run: ./gradlew clean build -x test
